variables:
    REGISTRY_HOST: hublab.example.com

stages:
    - build
    - deploy

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

build:
    stage: build
    script:
        - docker build -f compose/production/api/Dockerfile
        - docker build -f compose/production/frontend/Dockerfile
        - docker build -f compose/production/nginx/Dockerfile

deploy:
    stage: deploy
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $REGISTRY_HOST
        - docker build -t $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA -t $REGISTRY_HOST/$CI_PROJECT_PATH:latest .
        - docker build -t $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA -t $REGISTRY_HOST/$CI_PROJECT_PATH:latest .
        - docker build -t $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA -t $REGISTRY_HOST/$CI_PROJECT_PATH:latest .
        - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA
        - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:latest
