version: '3'

services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
        networks:
            - database
            - admin

    mongoclient:
        image: mongoclient/mongoclient
        volumes:
            - mongoclient:/data/db
        ports:
            - 3000:3000
        networks:
            - admin

    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            - backend

    forum:
        image: node:lts
        volumes:
            - .:/app
        working_dir: /app
        command: npm run nx serve forum
        environment:
            - DB_HOST=mongodb
            - DB_PORT=27017
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
            - mongodb
        networks:
            - database
            - backend

    users:
        image: node:lts
        volumes:
            - .:/app
        working_dir: /app
        command: npm run nx serve users
        environment:
            - DB_HOST=mongodb
            - DB_PORT=27017
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
            - mongodb
        networks:
            - database
            - backend

    frontend:
        build:
            context: .
            dockerfile: compose/local/frontend/Dockerfile
        volumes:
            - .:/app
        working_dir: /app
        command: nx serve agora-desktop "--host=0.0.0.0"
        networks:
            - frontend

    nginx:
        build:
            context: .
            dockerfile: compose/local/nginx/Dockerfile
        depends_on:
            - forum
            - users
            - frontend
        ports:
            - 8000:8000
        networks:
            - backend
            - frontend

volumes:
    mongodb_data_container: {}
    mongoclient: {}

networks:
    admin:
    database:
    backend:
    frontend:
