version: '3'

services:
    mongodb:
        image: mongo:latest
        expose:
          - 27017
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

    redis:
        image: redis
        ports:
            - 6379:6379

    forum:
        image: node:lts
        volumes:
            - .:/app
        working_dir: /app
        command: npm run nx serve forum
        environment:
            - DB_HOST=mongodb
            - DB_PORT=27017
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        expose:
            - 3333
        depends_on:
            - redis
            - mongodb

    users:
        image: node:lts
        volumes:
            - .:/app
        working_dir: /app
        command: npm run nx serve users
        environment:
            - DB_HOST=mongodb
            - DB_PORT=27017
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        expose:
            - 3333
        depends_on:
            - redis
            - mongodb

    nginx:
        build:
            context: .
            dockerfile: nginx/local/Dockerfile
        depends_on:
            - forum
            - users
        ports:
            - '3000:3000'
volumes:
    mongodb_data_container: {}
