version: '3'

services:
    forum:
        build:
            context: .
            dockerfile: compose/production/forum/Dockerfile
        expose:
            - 3333
        depends_on:
            - redis
            - mongodb

    users:
        build:
            context: .
            dockerfile: compose/production/users/Dockerfile
        expose:
            - 3333
        depends_on:
            - redis
            - mongodb

    nginx:
        build:
            context: .
            dockerfile: nginx/local/Dockerfile
        depends_on:
            - forum
            - users
        ports:
            - '3000:3000'
volumes:
    mongodb_data_container: {}
