version: '3'

services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

    api:
        build:
            context: .
            dockerfile: compose/production/api/Dockerfile
        depends_on:
            - mongodb
        environment:
            - DB_HOST=mongodb
            - DB_PORT=27017

    frontend:
        build:
            context: .
            dockerfile: compose/production/frontend/Dockerfile

    nginx:
        build:
            context: .
            dockerfile: compose/production/nginx/Dockerfile
        depends_on:
            - api
            - frontend
        ports:
            - 80:8000

volumes:
    mongodb_data_container: {}
