version: '3'

services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017

    api:
        image: node:lts-slim
        volumes:
            - .:/app
        working_dir: /app
        command: npm run test api
        depends_on:
            - mongodb
        environment:
            - DB_HOST=mongodb
            - DB_PORT=27017

    frontend:
        image: node:lts-slim
        volumes:
            - .:/app
        working_dir: /app
        command: npm run test agora-desktop
