version: '3'

services:
    mongodb_container:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

    redis:
        image: redis
        ports:
            - 6379:6379

volumes:
    mongodb_data_container:
