version: '3'

services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

    redis:
        image: redis
        ports:
            - 6379:6379

    forum:
        build:
            context: .
            dockerfile: compose/local/forum/Dockerfile
        expose:
            - 3333
        depends_on:
            - redis
            - mongodb

    users:
        build:
            context: .
            dockerfile: compose/local/users/Dockerfile
        expose:
            - 3333
        depends_on:
            - redis
            - mongodb

    nginx:
        build:
            context: .
            dockerfile: nginx/local/Dockerfile
        depends_on:
            - forum
            - users
        ports:
            - '3000:3000'
volumes:
    mongodb_data_container: {}
