version: '3'

services:
    worker:
        image: node:lts
        volumes:
            - .:/app


    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
        networks:
            - database

    frontend:
        build:
            context: .
            dockerfile: compose/production/frontend/Dockerfile
        networks:
            - frontend
        depends_on:
            - worker

    api:
        build:
            context: .
            dockerfile: compose/production/api/Dockerfile
        environment:
            - DB_HOST=mongodb
            - DB_PORT=27017
        depends_on:
            - worker
            - mongodb
        networks:
            - backend
            - database

    nginx:
        build:
            context: .
            dockerfile: compose/production/nginx/Dockerfile
        depends_on:
            - frontend
            - api
        ports:
            - 8000:80
        networks:
            - backend
            - frontend
volumes:
    mongodb_data_container: {}

networks:
    database:
    backend:
    frontend:
