version: '3'

services:
    frontend:
        build:
            context: .
            dockerfile: compose/production/frontend/Dockerfile

    api:
        build:
            context: .
            dockerfile: compose/production/api/Dockerfile
        environment:
            - DB_HOST=mongodb+srv://root:kFK^pYe&NYO42&ecb6kE@cluster0-lvke5.mongodb.net/test?retryWrites=true&w=majority
            - DB_PORT=27017
    nginx:
        build:
            context: .
            dockerfile: compose/production/nginx/Dockerfile
        depends_on:
            - frontend
            - api
        ports:
            - '3000:3000'
volumes:
    mongodb_data_container: {}
