version: '3'

services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

    mongoclient:
        image: mongoclient/mongoclient
        volumes:
            - mongoclient:/data/db
        ports:
            - 3000:3000

    api:
        image: node:lts-slim
        volumes:
            - .:/app
        working_dir: /app
        command: npm run ng serve api
        depends_on:
            - mongodb
        environment:
            - DB_HOST=mongodb
            - DB_PORT=27017

    frontend:
        build:
            context: .
            dockerfile: compose/local/frontend/Dockerfile
        volumes:
            - .:/app
        working_dir: /app
        command: nx run agora-desktop:serve-ssr "--host=0.0.0.0"

    nginx:
        build:
            context: .
            dockerfile: compose/local/nginx/Dockerfile
        depends_on:
            - api
            - frontend
        ports:
            - 8000:8000

volumes:
    mongodb_data_container: {}
    mongoclient: {}
