name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
                mongodb-version: [4.2]

        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.3.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}
                  mongodb-replica-set: insert-replica-set-name
            - name: node_modules
              run: npm ci
            - name: lint
              run: npm run lint
            - name: build
              run: npm run build:all
            - name: test
              run: npm run test
